"Cartridge.MD5" "012b8e6ef3b5fd5aabc94075c527709d"
"Cartridge.Manufacturer" "Arcadia Corporation, Dennis Caswell"
"Cartridge.ModelNo" "AR-4302"
"Cartridge.Name" "Party Mix (1983) (Arcadia)"
"Cartridge.Note" "Uses the Paddle Controllers"
"Controller.Left" "PADDLES"
"Controller.Right" "PADDLES"
"Controller.MouseAxis" "01"
"Display.YStart" "24"
""
