"Cartridge.MD5" "0c80751f6f7a3b370cc9e9f39ad533a7"
"Cartridge.Manufacturer" "Atari, Carla Meninsky"
"Cartridge.ModelNo" "CX2610"
"Cartridge.Name" "Warlords (1981) (Atari) (PAL)"
"Cartridge.Note" "Uses the Paddle Controllers"
"Controller.Left" "PADDLES"
"Controller.Right" "PADDLES"
"Controller.MouseAxis" "01"
""
