"Cartridge.MD5" "10f0ecaf962aef1fc28abed870b01b65"
"Cartridge.Manufacturer" "Atari, Paul Donaldson"
"Cartridge.Name" "Bionic Breakthrough (06-22-1984) (Atari) (Prototype)"
"Cartridge.Note" "Uses the Mindlink Controller"
"Cartridge.Rarity" "Prototype"
"Controller.Left" "MINDLINK"
""
