"Cartridge.MD5" "1802cc46b879b229272501998c5de04f"
"Cartridge.Manufacturer" "Atari, Christopher H. Omarzu - Children's Computer Workshop"
"Cartridge.ModelNo" "CX26104"
"Cartridge.Name" "Big Bird's Egg Catch (1983) (Atari)"
"Cartridge.Note" "Uses Kids/Keypad Controllers"
"Cartridge.Rarity" "Rare"
"Controller.Left" "KEYBOARD"
"Controller.Right" "KEYBOARD"
""
