"Cartridge.MD5" "274d17ccd825ef9c728d68394b4569d2"
"Cartridge.Manufacturer" "Playaround - J.H.M."
"Cartridge.ModelNo" "202"
"Cartridge.Name" "Bachelorette Party (1982) (Playaround)"
"Cartridge.Note" "AKA Bachelor Party, Uses the paddle controllers"
"Cartridge.Rarity" "Extremely Rare"
"Controller.Left" "PADDLES_IAXIS"
"Display.YStart" "22"
"Display.Height" "222"
"Display.Phosphor" "YES"
""
