"Cartridge.MD5" "2ae700c9dba843a68dfdca40d7d86bd6"
"Cartridge.Manufacturer" "TechnoVision - Thomas Jentzsch"
"Cartridge.Name" "Pharaoh's Curse (Thomas Jentzsch)"
"Cartridge.Note" "NTSC Conversion"
"Cartridge.Rarity" "Homebrew"
"Display.YStart" "40"
"Display.Height" "240"
"Display.Phosphor" "YES"
""
