"Cartridge.MD5" "47911752bf113a2496dbb66c70c9e70c"
"Cartridge.Manufacturer" "Atari, Christopher H. Omarzu, Preston Stuart, Bruce Williams"
"Cartridge.ModelNo" "CX26101"
"Cartridge.Name" "Oscar's Trash Race (1983) (Atari) (PAL)"
"Cartridge.Note" "Uses the Keypad Controllers"
"Controller.Left" "KEYBOARD"
"Controller.Right" "KEYBOARD"
""
