"Cartridge.MD5" "5b124850de9eea66781a50b2e9837000"
"Cartridge.Manufacturer" "PlayAround - J.H.M."
"Cartridge.ModelNo" "205"
"Cartridge.Name" "Bachelor Party (1982) (PlayAround)"
"Cartridge.Note" "Uses the paddle controllers"
"Cartridge.Rarity" "Extremely Rare"
"Controller.Left" "PADDLES_IAXIS"
"Display.YStart" "22"
"Display.Height" "222"
"Display.Phosphor" "YES"
""
