"Cartridge.MD5" "605fd59bfef88901c8c4794193a4cbad"
"Cartridge.Manufacturer" "Data Age"
"Cartridge.Name" "Secret Agent (1983) (Data Age) (Prototype)"
"Cartridge.Note" "Uses the Paddle Controllers"
"Cartridge.Rarity" "Prototype"
"Controller.Left" "PADDLES"
"Controller.MouseAxis" "01"
"Display.YStart" "38"
""
