"Cartridge.MD5" "6b75f8fa4fd011a6698c58315f83d2ac"
"Cartridge.Manufacturer" "Thomas Jentzsch"
"Cartridge.Name" "Sprintmaster DC (TJ)"
"Cartridge.Note" "Uses the Driving Controllers, Hack of Sprintmaster (Atari)"
"Cartridge.Rarity" "New Release (Hack)"
"Controller.Left" "DRIVING"
"Controller.Right" "DRIVING"
"Controller.MouseAxis" "45"
"Display.YStart" "24"
""
