"Cartridge.MD5" "6ed5012793f5ddf4353a48c11ea9b8d3"
"Cartridge.Manufacturer" "Arcadia Corporation, Dennis Caswell"
"Cartridge.ModelNo" "AR-4302"
"Cartridge.Name" "Party Mix - Down on the Line (3 of 3) (1983) (Arcadia)"
"Cartridge.Note" "Uses Paddle Controllers"
"Controller.Left" "PADDLES_IAXIS"
"Controller.Right" "PADDLES"
"Controller.MouseAxis" "01"
"Display.YStart" "30"
""
