"Cartridge.MD5" "75169c08b56e4e6c36681e599c4d8cc5"
"Cartridge.Manufacturer" "M Network, Hal Finney - INTV"
"Cartridge.ModelNo" "MT5666"
"Cartridge.Name" "Astroblast (1982) (M Network)"
"Cartridge.Note" "Can also use left joystick"
"Cartridge.Rarity" "Uncommon"
"Controller.Left" "PADDLES"
"Controller.SwapPaddles" "YES"
""
