"Cartridge.MD5" "798b8921276eec9e332dfcb47a2dbb17"
"Cartridge.Manufacturer" "Atari, Gary Stark"
"Cartridge.ModelNo" "CX26102"
"Cartridge.Name" "Cookie Monster Munch (1983) (Atari) (PAL) [a]"
"Cartridge.Note" "Uses Kids/Keypad Controllers"
"Controller.Left" "KEYBOARD"
"Controller.Right" "KEYBOARD"
""
