"Cartridge.MD5" "81414174f1816d5c1e583af427ac89fc"
"Cartridge.Manufacturer" "Thomas Jentzsch"
"Cartridge.Name" "Treasure Below (Thomas Jentzsch)"
"Cartridge.Note" "NTSC Conversion"
"Cartridge.Rarity" "Homebrew"
"Console.RightDifficulty" "A"
"Display.YStart" "20"
"Display.Height" "230"
""
