"Cartridge.MD5" "84df0704e6c777e1f9a16ec92ad80df0"
"Cartridge.Manufacturer" "Gray Games & AtariAge"
"Cartridge.Name" "E.T. Book Cart (PAL60)"
"Cartridge.Note" "Charles F. Gray & Michael Rideout"
"Display.Format" "PAL60"
"Display.YStart" "15"
"Display.Height" "240"
"Display.Phosphor" "YES"
"Display.PPBlend" "55"
""
