"Cartridge.MD5" "9f48eeb47836cf145a15771775f0767a"
"Cartridge.Manufacturer" "Atari, Warren Robinett"
"Cartridge.ModelNo" "CX2620"
"Cartridge.Name" "Basic Programming (1979) (Atari)"
"Cartridge.Note" "Uses Keypad Controllers"
"Cartridge.Rarity" "Rare"
"Controller.Left" "KEYBOARD"
"Controller.Right" "KEYBOARD"
"Display.Phosphor" "YES"
""
