"Cartridge.MD5" "aaea37b65db9e492798f0105a6915e96"
"Cartridge.Manufacturer" "Arcadia Corporation, Dennis Caswell"
"Cartridge.ModelNo" "AR-4302"
"Cartridge.Name" "Party Mix - Tug of War (2 of 3) (1983) (Arcadia)"
"Cartridge.Note" "Uses Paddle Controllers"
"Controller.Left" "PADDLES"
"Controller.Right" "PADDLES"
"Controller.MouseAxis" "02"
"Display.YStart" "30"
""
