"Cartridge.MD5" "ae2f1f69bb38355395c1c75c81acc644"
"Cartridge.Manufacturer" "Parker Brothers, Wilfredo 'Willy' Aguilar, Michael Becker, Neil McKenzie, Bob Smith, Brad Stewart"
"Cartridge.ModelNo" "PB5540"
"Cartridge.Name" "Star Wars - The Arcade Game (12-23-1983) (Parker Bros) (Prototype)"
"Cartridge.Rarity" "Prototype"
"Display.Phosphor" "YES"
""
