"Cartridge.MD5" "b98cc2c6f7a0f05176f74f0f62c45488"
"Cartridge.Manufacturer" "Spectravideo"
"Cartridge.ModelNo" "SV-010"
"Cartridge.Name" "CompuMate (1983) (Spectravideo)"
"Cartridge.Type" "CM"
"Controller.Left" "COMPUMATE"
"Controller.Right" "COMPUMATE"
"Display.Format" "NTSC"
"Display.Phosphor" "YES"
""
