"Cartridge.MD5" "c9f6e521a49a2d15dac56b6ddb3fb4c7"
"Cartridge.Manufacturer" "Parker Brothers, Rex Bradford"
"Cartridge.ModelNo" "PB5000"
"Cartridge.Name" "Star Wars - Jedi Arena (1983) (Parker Bros)"
"Cartridge.Note" "Uses the Paddle Controllers (swapped)"
"Controller.Left" "PADDLES"
"Controller.SwapPaddles" "YES"
"Controller.MouseAxis" "10"
"Display.YStart" "30"
""
