"Cartridge.MD5" "cddabfd68363a76cd30bee4e8094c646"
"Cartridge.Manufacturer" "Computer Magic - CommaVid, John Bronstein"
"Cartridge.ModelNo" "CM-001"
"Cartridge.Name" "MagiCard (1981) (CommaVid)"
"Cartridge.Note" "Uses the Keypad Controllers"
"Controller.Left" "KEYBOARD"
"Controller.Right" "KEYBOARD"
"Display.YStart" "24"
""
