"Cartridge.MD5" "df95e4af466c809619299f49ece92365"
"Cartridge.Manufacturer" "Atari, Michael Callahan, Preston Stuart"
"Cartridge.ModelNo" "CX26103"
"Cartridge.Name" "Alpha Beam with Ernie (06-03-1983) (Atari) (Prototype) (PAL)"
"Cartridge.Note" "Uses Keypad Controllers"
"Cartridge.Rarity" "Prototype"
"Controller.Left" "KEYBOARD"
"Controller.Right" "KEYBOARD"
""
