"Cartridge.MD5" "e7f005ddb6902c648de098511f6ae2e5"
"Cartridge.Manufacturer" "Spectravideo - Universum"
"Cartridge.ModelNo" "SV-010"
"Cartridge.Name" "CompuMate (1983) (Spectravideo) (PAL)"
"Cartridge.Type" "CM"
"Controller.Left" "COMPUMATE"
"Controller.Right" "COMPUMATE"
"Display.Format" "PAL"
"Display.Phosphor" "YES"
""
