"Cartridge.MD5" "f71694bd8e89d5a28daa73bf856635df"
"Cartridge.Manufacturer" "Gray Games & AtariAge"
"Cartridge.Name" "E.T. Book Cart (NTSC)"
"Cartridge.Note" "Charles F. Gray & Michael Rideout"
"Display.YStart" "15"
"Display.Height" "240"
"Display.Phosphor" "YES"
"Display.PPBlend" "55"
""
