"Cartridge.MD5" "f7424985bac41067502b4a05b64cb75a"
"Cartridge.Manufacturer" "Activision, Steve Cartwright"
"Cartridge.ModelNo" "AX-027"
"Cartridge.Name" "Plaque Attack (1983) (Activision)"
"Cartridge.Note" "Genesis controller (B is fire up, C is fire down)"
"Cartridge.Rarity" "Hack of Plaque Attack"
"Controller.Left" "GENESIS"
"Controller.Right" "GENESIS"
""
