"Cartridge.MD5" "f91fb8da3223b79f1c9a07b77ebfa0b2"
"Cartridge.Manufacturer" "Atari, Alan J. Murphy, Nick 'Sandy Maiwald' Turner - Sears"
"Cartridge.ModelNo" "CX2615 - 49-75140"
"Cartridge.Name" "Demons to Diamonds (1982) (Atari)"
"Cartridge.Note" "Uses the Paddle Controllers (left only)"
"Controller.Left" "PADDLES"
"Controller.SwapPaddles" "YES"
"Controller.MouseAxis" "10"
""
