"Cartridge.MD5" "fa1b060fd8e0bca0c2a097dcffce93d3"
"Cartridge.Manufacturer" "Atari, Christopher H. Omarzu, Preston Stuart, Bruce Williams"
"Cartridge.ModelNo" "CX26101"
"Cartridge.Name" "Oscar's Trash Race (1983) (Atari)"
"Cartridge.Note" "Uses the Keypad Controllers"
"Controller.Left" "KEYBOARD"
"Controller.Right" "KEYBOARD"
""
