"Cartridge.MD5" "ff3bd0c684f7144aeaa18758d8281a78"
"Cartridge.Manufacturer" "Atari, Bob Whitehead"
"Cartridge.ModelNo" "CX2651"
"Cartridge.Name" "Blackjack (1977) (Atari) (PAL)"
"Cartridge.Note" "Uses the Paddle Controllers"
"Cartridge.Rarity" "Rare"
"Controller.Left" "PADDLES_IAXIS"
"Display.YStart" "48"
""
