"Cartridge.MD5" "05b45ba09c05befa75ac70476829eda0"
"Cartridge.Manufacturer" "Parker Brothers, Rex Bradford"
"Cartridge.ModelNo" "931507"
"Cartridge.Name" "Star Wars - Jedi Arena (1983) (Parker Bros) (PAL)"
"Cartridge.Note" "Uses the Paddle Controllers (swapped)"
"Controller.Left" "PADDLES"
"Controller.SwapPaddles" "YES"
"Controller.MouseAxis" "10"
""
