"Cartridge.MD5" "08f4dc6f118f7c98e2406c180c08e78e"
"Cartridge.Manufacturer" "Arcadia Corporation, Dennis Caswell"
"Cartridge.ModelNo" "AR-4302"
"Cartridge.Name" "Party Mix - Tug of War (2 of 3) (1983) (Arcadia) (PAL)"
"Cartridge.Note" "Uses Paddle Controllers"
"Controller.Left" "PADDLES"
"Controller.Right" "PADDLES"
"Controller.MouseAxis" "02"
""
