"Cartridge.MD5" "0aa208060d7c140f20571e3341f5a3f8"
"Cartridge.Manufacturer" "U.S. Games Corporation,  Jeff Corsiglia, Paul Allen Newell"
"Cartridge.ModelNo" "VC1009"
"Cartridge.Name" "Towering Inferno (1982) (U.S. Games)"
"Cartridge.Note" "Uses the Joystick Controllers (swapped)"
"Console.SwapPorts" "YES"
"Display.YStart" "30"
"Display.Height" "220"
"Display.Phosphor" "YES"
""
