"Cartridge.MD5" "1619bc27632f9148d8480cd813aa74c3"
"Cartridge.Manufacturer" "Thomas Jentzsch"
"Cartridge.Name" "Steeple Chase (Thomas Jentzsch)"
"Cartridge.Note" "NTSC Conversion"
"Cartridge.Rarity" "Homebrew"
"Console.RightDifficulty" "A"
"Display.YStart" "20"
"Display.Height" "220"
"Display.Phosphor" "YES"
""
