"Cartridge.MD5" "170e7589a48739cfb9cc782cbb0fe25a"
"Cartridge.Manufacturer" "M Network, Hal Finney - INTV"
"Cartridge.ModelNo" "MT5666"
"Cartridge.Name" "Astroblast (1982) (M Network) [fixed]"
"Cartridge.Note" "Can also use left joystick"
"Cartridge.Rarity" "Uncommon"
"Controller.Left" "PADDLES"
"Controller.SwapPaddles" "YES"
""
