"Cartridge.MD5" "23fad5a125bcd4463701c8ad8a0043a9"
"Cartridge.Manufacturer" "CCE"
"Cartridge.ModelNo" "C-840"
"Cartridge.Name" "Stone Age (1983) (CCE)"
"Cartridge.Note" "Uses the Joystick Controllers (swapped)"
"Console.SwapPorts" "YES"
"Console.LeftDifficulty" "A"
"Console.RightDifficulty" "A"
"Display.YStart" "26"
"Display.Height" "220"
"Display.Phosphor" "YES"
""
