"Cartridge.MD5" "24d9a55d8f0633e886a1b33ee1e0e797"
"Cartridge.Manufacturer" "Thomas Jentzsch"
"Cartridge.Name" "Dragon Defender (Thomas Jentzsch)"
"Cartridge.Note" "NTSC Conversion"
"Cartridge.Rarity" "Homebrew"
"Display.YStart" "15"
"Display.Height" "240"
"Display.Phosphor" "YES"
""
