"Cartridge.MD5" "2dbdca3058035d2b40c734dcf06a86d9"
"Cartridge.Manufacturer" "Thomas Jentzsch"
"Cartridge.Name" "Asteroids DC+ (Thomas Jentzsch) (Hack)"
"Cartridge.Note" "Uses the Joystick (left) or Steering (right) Controller"
"Cartridge.Rarity" "Hack"
"Controller.Right" "DRIVING"
"Controller.MouseAxis" "58"
"Display.Phosphor" "YES"
""
