"Cartridge.MD5" "36c31bb5daeb103f488c66de67ac5075"
"Cartridge.Manufacturer" "Arcadia Corporation, Dennis Caswell"
"Cartridge.ModelNo" "AR-4302"
"Cartridge.Name" "Party Mix - Bop a Buggy (1 of 3) (1983) (Arcadia)"
"Cartridge.Note" "Uses Paddle Controllers"
"Controller.Left" "PADDLES"
"Controller.Right" "PADDLES"
"Controller.MouseAxis" "01"
"Display.YStart" "30"
""
