"Cartridge.MD5" "4bcc7f6ba501a26ee785b7efbfb0fdc8"
"Cartridge.Manufacturer" "Atari, Andrew Fuchs, Courtney Granner, Jeffrey Gusman, Mark R. Hahn"
"Cartridge.ModelNo" "CX2690"
"Cartridge.Name" "Pengo (1983) (Atari) (Prototype)"
"Cartridge.Rarity" "Prototype"
""
