"Cartridge.MD5" "4c0fb2544ae0f8b5f7ae8bce7bd7f134"
"Cartridge.Manufacturer" "Arcadia Corporation, Dennis Caswell"
"Cartridge.ModelNo" "AR-4302"
"Cartridge.Name" "Party Mix (Preview) (1983) (Arcadia)"
"Cartridge.Note" "Uses the Paddle Controllers"
"Controller.Left" "PADDLES"
"Controller.Right" "PADDLES"
"Display.YStart" "24"
""
