"Cartridge.MD5" "6a07836c382195dd5305ce61d992aaa6"
"Cartridge.Manufacturer" "Apollo, Larry Martin"
"Cartridge.ModelNo" "AP-2008"
"Cartridge.Name" "Guardian (1982) (Apollo) (Prototype)"
"Cartridge.Note" "Uses the Paddle Controller (left only)"
"Cartridge.Rarity" "Prototype"
"Controller.Left" "PADDLES"
"Controller.MouseAxis" "01"
""
