"Cartridge.MD5" "7da9de8d62fcdd3a2c545b2e720c2a61"
"Cartridge.Manufacturer" "CommaVid, John Bronstein"
"Cartridge.ModelNo" "CM-001"
"Cartridge.Name" "MagiCard (1981) (CommaVid) (4K)"
"Cartridge.Note" "Uses the Keypad Controllers"
"Controller.Left" "KEYBOARD"
"Controller.Right" "KEYBOARD"
"Display.YStart" "24"
""
