"Cartridge.MD5" "7ef3ca08abde439c6ccca84693839c57"
"Cartridge.Manufacturer" "Arcadia Corporation, Dennis Caswell"
"Cartridge.ModelNo" "AR-4302"
"Cartridge.Name" "Party Mix (1983) (Arcadia) (PAL)"
"Cartridge.Note" "Uses the Paddle Controllers"
"Controller.Left" "PADDLES"
"Controller.Right" "PADDLES"
"Controller.MouseAxis" "01"
""
