"Cartridge.MD5" "8a9d874a38608964f33ec0c35cab618d"
"Cartridge.Manufacturer" "Chris Cracknell"
"Cartridge.Name" "Rescue Bira Bira (Chris Cracknell)"
"Cartridge.Note" "Hack of Jungle Fever"
"Cartridge.Rarity" "Hack"
"Display.YStart" "20"
"Display.Height" "230"
"Display.Phosphor" "YES"
""
