"Cartridge.MD5" "8f5ac5139419c5d49bacc296e342a247"
"Cartridge.Manufacturer" "Atari, Michael Callahan, Preston Stuart"
"Cartridge.ModelNo" "CX26103"
"Cartridge.Name" "Alpha Beam with Ernie (12-22-1983) (Atari) (Prototype)"
"Cartridge.Note" "Uses Keypad Controllers"
"Cartridge.Rarity" "Prototype"
"Controller.Left" "KEYBOARD"
"Controller.Right" "KEYBOARD"
""
