"Cartridge.MD5" "9947f1ebabb56fd075a96c6d37351efa"
"Cartridge.Manufacturer" "CBS Electronics"
"Cartridge.ModelNo" "4L 2737 0000"
"Cartridge.Name" "Omega Race (1983) (CBS Electronics)"
"Cartridge.Note" "Set right difficulty to 'A' for BoosterGrip in both ports"
"Console.RightDifficulty" "A"
"Controller.Left" "BOOSTERGRIP"
"Controller.Right" "BOOSTERGRIP"
""
