"Cartridge.MD5" "9e01f7f95cb8596765e03b9a36e8e33c"
"Cartridge.Manufacturer" "Atari, Michael Callahan, Preston Stuart"
"Cartridge.ModelNo" "CX26103"
"Cartridge.Name" "Alpha Beam with Ernie (1983) (Atari)"
"Cartridge.Note" "Uses Keypad Controllers"
"Cartridge.Rarity" "Rare"
"Controller.Left" "KEYBOARD"
"Controller.Right" "KEYBOARD"
""
