"Cartridge.MD5" "a47e26096de6f6487bf5dd2d1cced294"
"Cartridge.Manufacturer" "Atari, Larry Kaplan"
"Cartridge.ModelNo" "CX2643"
"Cartridge.Name" "Codebreaker (1978) (Atari) (PAL)"
"Cartridge.Note" "Uses Keypad Controllers"
"Controller.Left" "KEYBOARD"
"Controller.Right" "KEYBOARD"
"Display.YStart" "57"
""
