"Cartridge.MD5" "b061e98a4c854a672aadefa233236e51"
"Cartridge.Manufacturer" "Atari, Warren Robinett"
"Cartridge.ModelNo" "CX2620, CX2620P"
"Cartridge.Name" "Basic Programming (1979) (Atari) (PAL)"
"Cartridge.Note" "Uses Keypad Controllers"
"Cartridge.Rarity" "Common"
"Controller.Left" "KEYBOARD"
"Controller.Right" "KEYBOARD"
"Display.Phosphor" "YES"
""
