"Cartridge.MD5" "c52d9bbdc5530e1ef8e8ba7be692b01e"
"Cartridge.Manufacturer" "Atari, Robert C. Polaro"
"Cartridge.ModelNo" "CX26130"
"Cartridge.Name" "Holey Moley (02-29-1984) (Atari) (Prototype)"
"Cartridge.Note" "Uses Keypad Controllers"
"Cartridge.Rarity" "Prototype"
"Controller.Left" "KEYBOARD"
"Controller.Right" "KEYBOARD"
""
