"Cartridge.MD5" "c880c659cdc0f84c4a66bc818f89618e"
"Cartridge.Manufacturer" "Thomas Jentzsch"
"Cartridge.Name" "Open Sesame (Thomas Jentzsch)"
"Cartridge.Note" "NTSC Conversion"
"Cartridge.Rarity" "Homebrew"
"Display.YStart" "20"
"Display.Height" "254"
"Display.Phosphor" "YES"
""
