"Cartridge.MD5" "cfffc4b97d01cc3e7b9f47575f7b11ec"
"Cartridge.Manufacturer" "Xonox - K-Tel Software, Anthony R. Henderson"
"Cartridge.ModelNo" "99007, 6240"
"Cartridge.Name" "Tomarc the Barbarian (1983) (Xonox) (PAL60)"
"Cartridge.Note" "Genesis controller (B is jump and throw, C switches between players)"
"Cartridge.Rarity" "Hack of Tomarc the Barbarian"
"Controller.Left" "GENESIS"
"Display.Format" "PAL60"
""
