"Cartridge.MD5" "d00f6f8ba89559e4b20972a478fc0370"
"Cartridge.Manufacturer" "Spiceware"
"Cartridge.ModelNo" "SW-01"
"Cartridge.Name" "Medieval Mayhem (PAL)"
"Cartridge.Rarity" "Homebrew"
"Cartridge.Sound" "STEREO"
"Controller.Left" "PADDLES"
"Controller.Right" "PADDLES"
"Controller.MouseAxis" "01"
""
