"Cartridge.MD5" "d45ebf130ed9070ea8ebd56176e48a38"
"Cartridge.Manufacturer" "Sega"
"Cartridge.ModelNo" "001-01"
"Cartridge.Name" "Tac-Scan (1982) (Sega)"
"Cartridge.Note" "Uses the Paddle Controllers (right only)"
"Console.SwapPorts" "YES"
"Controller.Left" "PADDLES"
"Controller.SwapPaddles" "YES"
"Display.Height" "215"
"Display.Phosphor" "YES"
""
