"Cartridge.MD5" "d62283aed0f4199adb2333de4c263e9c"
"Cartridge.Manufacturer" "Atari, Alan J. Murphy, Nick 'Sandy Maiwald' Turner"
"Cartridge.ModelNo" "CX2615"
"Cartridge.Name" "Demons to Diamonds (1982) (Atari) (PAL)"
"Cartridge.Note" "Uses the Paddle Controllers (left only)"
"Controller.Left" "PADDLES"
"Controller.SwapPaddles" "YES"
"Controller.MouseAxis" "10"
""
