"Cartridge.MD5" "dbc7485ad5814d466de780a3e7ed3b46"
"Cartridge.Manufacturer" "Kyle Pittman"
"Cartridge.Name" "Pink Floyd (Kyle Pittman) (PD)"
"Cartridge.Note" "Hack of Adventures of Tron (Mattel)"
"Cartridge.Rarity" "New Release (Hack)"
""
