"Cartridge.MD5" "e40a818dac4dd851f3b4aafbe2f1e0c1"
"Cartridge.Manufacturer" "Atari, Bill Aspromonte, Dr. Lee Salk"
"Cartridge.ModelNo" "CX26137"
"Cartridge.Name" "Peek-A-Boo (1984) (Atari) (Prototype)"
"Cartridge.Note" "Uses the Keypad Controllers"
"Cartridge.Rarity" "Prototype"
"Controller.Left" "KEYBOARD"
"Controller.Right" "KEYBOARD"
""
