"Cartridge.MD5" "f283cc294ece520c2badf9da20cfc025"
"Cartridge.Manufacturer" "Atari, Christopher H. Omarzu - Children's Computer Workshop"
"Cartridge.ModelNo" "CX26104"
"Cartridge.Name" "Big Bird's Egg Catch (1983) (Atari) (PAL)"
"Cartridge.Note" "Uses Kids/Keypad Controllers"
"Cartridge.Rarity" "Rare"
"Controller.Left" "KEYBOARD"
"Controller.Right" "KEYBOARD"
""
