"Cartridge.MD5" "f4b8a47a95b61895e671c3ec86ffd461"
"Cartridge.Manufacturer" "Parker Brothers, Wilfredo 'Willy' Aguilar, Michael Becker, Neil McKenzie, Bob Smith, Brad Stewart"
"Cartridge.ModelNo" "PB5540"
"Cartridge.Name" "Star Wars - The Arcade Game (01-03-1984) (Parker Bros) (Prototype)"
"Cartridge.Rarity" "Prototype"
"Display.Phosphor" "YES"
""
