"Cartridge.MD5" "f7fac15cf54b55c5597718b6742dbec2"
"Cartridge.Manufacturer" "Spiceware"
"Cartridge.ModelNo" "SW-01"
"Cartridge.Name" "Medieval Mayhem (NTSC)"
"Cartridge.Rarity" "Homebrew"
"Cartridge.Sound" "STEREO"
"Controller.Left" "PADDLES"
"Controller.Right" "PADDLES"
"Controller.MouseAxis" "01"
""
