"Cartridge.MD5" "fa98d48cd609c9babc819e0a1bd8d598"
"Cartridge.Manufacturer" "AtariAge (Chris Walton)"
"Cartridge.Name" "Juno First (2009) (PAL60)"
"Cartridge.Note" "AtariVox supported"
"Cartridge.Rarity" "Homebrew"
"Controller.Right" "ATARIVOX"
"Display.Format" "PAL60"
"Display.Phosphor" "YES"
""
