"Cartridge.MD5" "ff86fc8ffa717bb095e8471638c1c31c"
"Cartridge.Manufacturer" "Arcadia Corporation, Dennis Caswell"
"Cartridge.ModelNo" "AR-4302"
"Cartridge.Name" "Party Mix - Bop a Buggy (1 of 3) (1983) (Arcadia) (PAL)"
"Cartridge.Note" "Uses Paddle Controllers"
"Controller.Left" "PADDLES"
"Controller.Right" "PADDLES"
"Controller.MouseAxis" "01"
""
